version: '2.2'

services:
    #database: use budgetcontrole CORE database https://github.com/BudgetControl/Core
    website:
      container_name: budgetcontrol-website
      image: budgetcontrol/core:v2.2
      volumes:
        - ./:/var/www/workdir
      networks:
        - budgetcontrol_network
      restart: unless-stopped

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
